	/*
	 *  -- RESET
	  
	  TRUNCATE TABLE DATA_VAULT."PUBLIC".PART_H;
	  TRUNCATE TABLE DATA_VAULT."PUBLIC".SUPPLIER_H;
	  TRUNCATE TABLE DATA_VAULT."PUBLIC".SUPPLIER_INVENTORY_H;
	 */


	USE DATABASE SNOWFLAKE_SAMPLE_DATA;

	USE SCHEMA TPCH_SF10;

	SET REC_SRC = 'SNOWFLAKE_SAMPLE_DATABASE';

	USE WAREHOUSE WH_ETL_HUBS; 

	-----------------
	-- Part Hub
	-----------------	
		INSERT INTO DATA_VAULT."PUBLIC".PART_H
			(PART_PK,PART_BK,LOAD_DTS,REC_SRC)

		SELECT 	MD5(P.P_PARTKEY) AS PK 	-- Add preferred Hashing approach 
				,P.P_PARTKEY
				,CURRENT_TIMESTAMP() 	CT				
				,$REC_SRC				RS
		FROM PART P
		WHERE PK NOT IN (SELECT H.PART_PK FROM DATA_VAULT."PUBLIC".PART_H H);
		
	-----------------
	-- Supplier Hub
	-----------------	
		INSERT INTO DATA_VAULT."PUBLIC".SUPPLIER_H
				(SUPPLIER_PK,SUPPLIER_BK,LOAD_DTS,REC_SRC)
													
		SELECT 	MD5(S.S_SUPPKEY) AS PK  -- Add preferred Hashing approach 
				,S.S_SUPPKEY
				,CURRENT_TIMESTAMP() 	CT
				,$REC_SRC				RS
		FROM SUPPLIER S
		WHERE PK NOT IN (SELECT H.SUPPLIER_PK FROM DATA_VAULT."PUBLIC".SUPPLIER_H H);			
		
	-----------------
	-- Inventory Hub
	-----------------
	
		INSERT INTO DATA_VAULT."PUBLIC".SUPPLIER_INVENTORY_H
				(INVENTORY_PK,INVENTORY_BK,LOAD_DTS,REC_SRC)
		SELECT MD5(PS_PARTKEY || PS_SUPPKEY) 	AS INVENTORY_PK -- Add preferred Hashing approach
				,PS_PARTKEY || PS_SUPPKEY 	 	AS INVENTORY_BK					
				,CURRENT_TIMESTAMP() 	CT					
				,$REC_SRC				RS
				--,'' RS
		FROM PARTSUPP P
		WHERE INVENTORY_PK NOT IN (SELECT H.INVENTORY_PK FROM DATA_VAULT."PUBLIC".SUPPLIER_INVENTORY_H H);
			
		
		